### ISSUE TITLE
OOOP didnt click the GL button

### ISSUE THREAD

**Issue by PSschug** [unfoldingWord-dev/ts-requirements#105]
Joe has come off a Mast event with all the device tstudio files and Joe needs to merge them. In looking at all the different file names, and Joe just starts merging them. Joe keeps seeing that he comes up with 2 different projects of one book of the bible. Joe needs those projects to be joined in one project for the GL. Joe does remember that he didnt click the GL button till the start of the second week.

**Comment by ChrisJarka** [comment]
@PSschug What are the project names of the one book of the Bible?

**Comment by PSschug** [comment]
@ChrisJarka I believe there are multiple books like this in this one case I am talking about.

**Comment by ChrisJarka** [comment]
I thought that the GL button only opened up the editing options for the UDB, tW, tN, tQ and tA . It also affects how the translation of the books done in the ULB are saved?

**Comment by PSschug** [comment]
In the file name is only, for ULB and UDB only the others come in on their own name. This doesn’t have anything to do with the front end of inputting the translation. Only how things are merged and put in one file.

**Comment by klappy** [comment]
addressed.
