### ISSUE TITLE
Formatting in tW - not bolding

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-requirements#106]
See the attached. This was taken in tS-Desktop (tS-Android)shows the bolded font.)

![2016-05-11_7-46-55](https://cloud.githubusercontent.com/assets/9850185/15182426/60bffd24-175a-11e6-91e7-d587a339a62f.png)

**Comment by cdwhitfield73** [comment]
This is a duplicate request and the issue has already been resolved for Version 8
