### ISSUE TITLE
tS-Desktop footnotes not showing as expected

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-requirements#107]
Footnotes in the ULB are showing as verse text in Desktop. See highlighted text in this pic.
![2016-05-11_14-21-05](https://cloud.githubusercontent.com/assets/9850185/15194650/f397ef76-1791-11e6-81aa-0e372cbe997b.png)

**Comment by cckozie** [comment]
There is a similar issue in ts-desktop, #365. So I'm marking this one as a dup and closing it.
