### ISSUE TITLE
tS-D Settings Menu Items - reorganization

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-requirements#115]
The menu items are:
General (GL Mode, Font, Font Size)
Upload (Data Server, Media Server)
Advanced (Backup Location, Developer Tools, Refresh Settings)
About (App Version, Data Path)

Please consider this organization:
General (GL Mode, Font, Font Size, Backup Location) - all can be changed by end-user
_______________________________ Visible line (if not too hard)
About (App Version, Data Path) - view only data
Upload (Data Server, Media Server) - view only data
Advanced (Developer Tools, Refresh Settings) - view only data

**Comment by cdwhitfield73** [comment]
This is complete in Desktop.
