### ISSUE TITLE
tS-D Settings Menu additional items

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-requirements#116]
The menu items are:
General (GL Mode, Font, Font Size)
Upload (Data Server, Media Server)
Advanced (Backup Location, Developer Tools, Refresh Settings)
About (App Version, Data Path)

Please consider adding after the General section and before the Upload Section.
Legal - License Agreement, Statement of Faith, Translation Guidelines, Software Licenses

**Comment by cdwhitfield73** [comment]
This is complete in Desktop.
