### ISSUE TITLE
tS Should Use USFM Source Files

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-requirements#12]
Instead of the USX, tS should be using the USFM source files from the catalog.

~~This could include switching to use 1 file per book, to match the USFM standard.  Or, possibly compromise at 1 file per chapter.~~

@neutrinog and I determined that it would be better to keep the chunks as individual files, otherwise the app could get very confused.  The app will export as 1 file and we could create a simple export in Gogs to unify the files as well.  (see https://github.com/unfoldingWord-dev/gogs/issues/14)

**Comment by RRohrssen** [comment]
Create issues in Android and Desktop

**Comment by da1nerd** [comment]
This is blocked pending an api update

**Comment by klappy** [comment]
Will handle in later issue. Closing for now.
