### ISSUE TITLE
Display Splash/Launch Screen When Loading tS Desktop

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-requirements#18]
https://team43.slack.com/archives/devs/p1455715144000002

Dima Saifidinov [7:19 AM] 
@jag3773:  Our 3 translators installed TranslationStudio and they all wrote one comment. The program launch takes around 3 minutes. Jesse is the a way to put "loading pop up window" to show that program is loading? I had same issue. I thought something wrong, but TrS loaded. ITs not about loading time but to make sure that software is loading. Thanks

**Comment by RRohrssen** [comment]
Joe Gervais also requested this feature. https://team43.slack.com/archives/helpdesk/p1456423015000176

**Comment by RRohrssen** [comment]
Eric Steggerada is also interested in this feature.
https://team43.slack.com/archives/helpdesk/p1456478593000179

**Comment by RRohrssen** [comment]
The splash screen will display logo, and an animated message that indicates loading during the time between initial launch and first project selection screen.

**Comment by cdwhitfield73** [comment]
This is complete in Desktop.
