### ISSUE TITLE
Implement Link Format

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-requirements#23]
This issues requires that the server side content and the tS clients use the link format described here: https://github.com/unfoldingWord-dev/ts-requirements/wiki/Link-Format.
- [ ] Server side (code needs added to https://github.com/unfoldingWord-dev/tools/blob/master/uwb/tn-kt_export.py#L63).  Also, review of other links being pushed out in tA and all the content. https://github.com/unfoldingWord-dev/ts-server/issues/10
- [ ] Android https://github.com/unfoldingWord-dev/ts-android/issues/1323
- [ ] Desktop https://github.com/unfoldingWord-dev/ts-desktop/issues/433

**Comment by ChrisJarka** [comment]
@jag3773 The Link-Format page has the bible links as [[en:bible:gen:01-02]] example and really we have been putting it as (for example) [[en:bible:gen:01:22|1:24]] We have been using the pipe because we want to direct the translator to the exact verse to look at with the link to the chunk that the verse is in.
Do we need to rethink how we are adding Bible links in the tN?

**Comment by jag3773** [comment]
Note that once the server side code implements adding the Bible and OBS links into the tW articles, the OBS tW link should start pointing to the Bible tW JSON file.

**Comment by ChrisJarka** [comment]
Oh - you are referring to the bible links in the tWords! I was thinking of the links in the tNotes.
Sorry to mis-read/understand.

**Comment by jag3773** [comment]
@ChrisJarka you are correct in surfacing that issue, however.  The app can handle verse links, but Door43 does not.  I'm thinking it would be better use the verses as the links, even if Door43 doesn't support it right now.  What do you think?

**Comment by ChrisJarka** [comment]
Yes, we need to point to the exact verse that we want to be the example. Could you please provide an example for me to see before I confirm?
Could you bring this up at the Tuesday meeting - or does this need to be implemented earlier than that?

**Comment by RRohrssen** [comment]
Create new issues for this in Android and Desktop

**Comment by da1nerd** [comment]
This is blocked pending updates to the link formats.

**Comment by cckozie** [comment]
Has this been fixed in v11? I think at least some of it has.

**Comment by ChrisJarka** [comment]
Yes, in Desktop v11 it is working correctly.
