### ISSUE TITLE
tS Import/Export Compatibility

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-requirements#25]
Android and Desktop need to have _full_ import/export capability with one another, going both directions, for a Bible or OBS project.

**Comment by RRohrssen** [comment]
For Android: https://github.com/unfoldingWord-dev/ts-android/issues/1305

**Comment by jag3773** [comment]
Full specification at https://github.com/unfoldingWord-dev/ts-requirements/wiki/ts.Translator.TargetTranslation

**Comment by klappy** [comment]
Closing for now. When projects are found not compatible between the two from use cases, they will be addressed then with new issues.
