### ISSUE TITLE
tW Sorting

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-requirements#27]
Currently, the tW are being sorted alphabetically with case _sensitivity_.  I think it would be desirable to make this case _insensitive_.

This relates to the "Words Index" and the way they are listed as a translatable project.

**Comment by ChrisJarka** [comment]
What display are you referring to?
In the Bible Words listing? - It would be good to have it case insensitive AND to mix the obe:other and obe:kt terms.
In the chunk Word listing? - It would be best practice to list them as they are listed on Door43. That reflects the words as they appear in the text.

**Comment by ChrisJarka** [comment]
@neutrinog and @jag3773 I updated the tS app yesterday and today and now my tW in a Bible chunk are duplicated! Please note on the attached pic the duplication of tW in a chunk
![screenshot_20160225114113](https://cloud.githubusercontent.com/assets/9850185/13329290/0b937ff8-dbc1-11e5-864a-cb97d9a819db.png)

**Comment by jag3773** [comment]
@ChrisJarka please submit a bug report from your app for that issue.

**Comment by RRohrssen** [comment]
I think we can close this. The bug has been reported in Android.

**Comment by RRohrssen** [comment]
Each word is sorted case insensitive on the Word title for both Desktop and Android.

**Comment by cdwhitfield73** [comment]
This is complete in Desktop

**Comment by klappy** [comment]
Tagged issues closed.
