### ISSUE TITLE
Handle merge conflicts when publishing a translation

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord-dev/ts-requirements#30]
When publishing to the server we must first perform a pull to get any pending changes. If there was a merge conflict we need to display a notice to the user with the following options:
- Review conflicts - takes them back to their translation where they can view the conflicts
- Use my changes - favors the users changes and continues to push
- User server changes - favors the server changes and continues to push
- Cancel - rolls back the merge that resulted from the pull request

> NOTE: it would be nice to have a shortcut for jumping to the next/previous merge conflict while in the translate mode.

**Comment by RRohrssen** [comment]
Implement after GOGS

**Comment by da1nerd** [comment]
If the user clicks "Review conflicts" then enters back into the publishing work flow before actually resolving them #31 will come into play.

**Comment by da1nerd** [comment]
@jag3773  @klappy @RRohrssen this is an important issue to get resolved since this is a potential cause of data loss for users. Currently the publishing occurs as a "forced" (read `overwrite`) upload in order to ensure users are never blocked from publishing something. Can we bump this up in priority?

**Comment by klappy** [comment]
Thanks @neutrinog. If we bump this up in priority, do you mean looking at scheduling for the 7.0 cleanup? Or later in the 7.x to release for 8.0?

**Comment by da1nerd** [comment]
This will take some time so 8.0

**Comment by da1nerd** [comment]
This feature is deprecated in favor of https://github.com/unfoldingWord-dev/ts-requirements/issues/145
