### ISSUE TITLE
Block users from publishing if there are merge conflicts

### ISSUE THREAD

**Issue by da1nerd** [unfoldingWord-dev/ts-requirements#31]
In the review stage of publishing if there are merge conflicts they should not be allowed to continue to the next stage until they resolve all the merge conflicts. The review mode should display the merge conflict diff on the chunk to clearly indicate the conflict.

**Comment by RRohrssen** [comment]
Is this just a part of the requirements for #30?

**Comment by neutrinog** [comment]
@RRohrssen no this is a different issue. #30 is for when a merge arises as a result of publishing.This issue is when there were already merge conflicts.

**Comment by RRohrssen** [comment]
Implement after GOGS

**Comment by da1nerd** [comment]
the full spec on publishing is at https://github.com/unfoldingWord-dev/ts-requirements/wiki/Publishing
