### ISSUE TITLE
Allow font size to be set by the user

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-requirements#32]
This came from Joe Gervais.

need a way to increase font size in TS for visually challenged translators, particularly with using complex scripts (alphabets).

**Comment by RRohrssen** [comment]
Android may already be sufficient. Desktop needs a larger font size available.

**Comment by RRohrssen** [comment]
Android: https://github.com/unfoldingWord-dev/ts-android/issues/1310
Desktop: https://github.com/unfoldingWord-dev/ts-desktop/issues/395

**Comment by klappy** [comment]
Both tagged issues are closed.
