### ISSUE TITLE
Import translations by other users from GOGS

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-requirements#41]
Pulling from GOGS is assumed as part of this issue. An example may be pulling another users work from GOGS where merging a project needs to occur. There is currently a button in the import UI that needs to be linked to this functionality.

**Comment by RRohrssen** [comment]
After the user has successfully logged in, we need a browse/search function in order to find the translation they are trying to import.

**Comment by da1nerd** [comment]
when users begin browsing online we could ask "What language/project are you looking for?" We could use the same ui for starting target translation. In addition when starting a new target translation we could suggest checking online for a translation that has already been started (requires them to be online).

When importing a translation from someone else users don't need to be logged in.

It would be nice to have the repo forked on their gogs account. We could possibly do this only when they first push by looking in the git logs for the parent repo. This would allow users to pull down translations without being logged in.

The starting point of this could be in the "restore" menu.

**Comment by cdwhitfield73** [comment]
This is complete in Desktop
