### ISSUE TITLE
Headers in tA translation in tS-Desktop

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-requirements#44]
Would it be possible to add in the section headers for the translators? We have defined certain headers and it would be nice if they would continue with the same formatting of the pages. (thinking of further enhancements on the app)
![headers in ta translation screen ts-d](https://cloud.githubusercontent.com/assets/9850185/13716645/6b5ec8d0-e7aa-11e5-9752-8db32a7ae947.png)

**Comment by ChrisJarka** [comment]
I've noticed the same with translationWords. There is no way to 'set apart' the 'Translation Suggestions' in tS-Desktop. Is this not needed for the APP?
I've attached two screen shots for 'abomination': 1) in tS-D resources with heading of Translation Suggestions and 2) with the heading title lost in the translation (highlighted). I even entered twice for a blank line and then typed Translation Suggestions onto a separate line.
![abomination ts shows](https://cloud.githubusercontent.com/assets/9850185/13732498/94c786a6-e95a-11e5-957b-eb4b81e52cb3.png)
![abomination ts gets lost](https://cloud.githubusercontent.com/assets/9850185/13732500/987c96ba-e95a-11e5-9e3c-ad17d8eae942.png)

**Comment by RRohrssen** [comment]
Save for tS-Requirements Triage discussion

**Comment by RRohrssen** [comment]
Duplicate to the existing issue where Thomas is already working on the markdown editor. https://github.com/unfoldingWord-dev/ts-desktop/issues/354

**Comment by RRohrssen** [comment]
Issue moved to [unfoldingWord-dev/ts-desktop #469](https://github.com/unfoldingWord-dev/ts-desktop/issues/469) via [**ZenHub.io**](https://www.zenhub.io/)
