### ISSUE TITLE
Missing information on tW pages

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-requirements#45]
I've noticed a discrepancy in the translationWords in tS-Desktop v5.
For instance the tW- God, Adam, Christ and more...
In the OBS the sections of 'See Also:' and 'Examples from OBS:' show. 
While in the Galatians, those sections are not showing.

Shouldn't they show both from the Bible and OBS?

**Comment by RRohrssen** [comment]
Issue moved to [unfoldingWord-dev/ts-desktop #468](https://github.com/unfoldingWord-dev/ts-desktop/issues/468) via [**ZenHub.io**](https://www.zenhub.io/)
