### ISSUE TITLE
Error in formatting - tW

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-requirements#46]
I've noticed that the formatting marks for bolding are showing on the tW. See Adam. (This tW also has Eve listed twice as a See Also)
![adam - double eve and bolding marks](https://cloud.githubusercontent.com/assets/9850185/13732575/42cc77d8-e95c-11e5-8a64-aa016f19d30d.png)

**Comment by ChrisJarka** [comment]
Also on Abiathar - the 'See also' is showing the link syntax.
![abiathar](https://cloud.githubusercontent.com/assets/9850185/13732587/755d042e-e95c-11e5-8ede-9da062a4fe1b.png)

**Comment by RRohrssen** [comment]
Check which version she was on. This may have been fixed in the latest version.

**Comment by da1nerd** [comment]
I just verified the desktop version had a duplicate "Eve". Android just shows one though so it's likely not a source issue.

**Comment by ChrisJarka** [comment]
I'm using v5 for tS-D. Sorry I didn't add that information. My bad. :)

**Comment by ChrisJarka** [comment]
More information on Adam - The formatting for bold shows in OBS - editing chunks section
![adam showing bold formatting](https://cloud.githubusercontent.com/assets/9850185/13784590/3dee8f4e-eaa6-11e5-8f65-ec7e2cc9d0ff.png)

**Comment by ChrisJarka** [comment]
More information on Abiathar -
Bad formatting on the (See: links) is on the chunk view
![abiathar - bad formatting](https://cloud.githubusercontent.com/assets/9850185/13784632/67f1c0fe-eaa6-11e5-9449-0073b8069ee7.png)

And on the tW translation screen
![tw abiiathar - desktop](https://cloud.githubusercontent.com/assets/9850185/13784646/720c103a-eaa6-11e5-970e-3c91b6f69f4e.png)
@RRohrssen

**Comment by da1nerd** [comment]
Just to summarize:
- links are not rendered (in source text or in helps).
- the bold html tag is not rendered in the helps
- the term "Eve" is duplicating (see the term "Adam" in OBS). This is likely occurring due to miss-use of the `resource__translation_word` table.

**Comment by RRohrssen** [comment]
Issue moved to [unfoldingWord-dev/ts-desktop #474](https://github.com/unfoldingWord-dev/ts-desktop/issues/474) via [**ZenHub.io**](https://www.zenhub.io/)
