### ISSUE TITLE
Splash screen or some user feedback when restoring

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-requirements#47]
Todd Price [4:08 AM] 
joel: When restoring a project in tS Windows, there is a long delay before it tells you whether or not it has successfully restored. Could there be a "Loading...." splash screen or something so the user knows it is working?

**Comment by RRohrssen** [comment]
Chris says the code is there. He's checking with Todd to verify that it does work as expected.

Can we get Todd Price to verify.

**Comment by cckozie** [comment]
There should be some kind of "working on it" (spinning wheel, etc) whenever the there is a delay of more than one or two seconds before the requested activity is completed. Other examples of where there should be that indications: choosing the source language, loading Translation Academy, maybe more to come.

**Comment by cdwhitfield73** [comment]
Debugged the restore issue today and discovered the problem.  The code was there to display a loading window but the app was getting locked up by the backend code that was doing the restoring before the loading window could render.  This has been fixed.  There are loading windows on most other functions...however, the two that don't have something were accurately identified by Chris K above...choosing the source and loading tA display.

**Comment by toddlprice** [comment]
Sorry to say, it still has no splash screen when I try it. I re-downloaded and re-installed tS Desktop 5.0.0 to make sure I had the latest tS for Windows. (I'm running Win10). When I restored OBS it happened so fast there was no need for a splash screen but when I loaded Luke there was a delay of several seconds (probably 10-11) with no splash screen.

**Comment by cdwhitfield73** [comment]
This issue is complete and can be closed.
