### ISSUE TITLE
Losing translated text - tS 5.0.0 - Windows 10

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-requirements#48]
To replicate issue:
Start new project: Source = English, Target = English, OBS
Switch to chunking mode
Copy source title and paste in target (leave target on top)
Copy source story reference and paste in target (leave target on top)
Copy source frame 1 and paste in target (leave target on top)
Copy source frame 2 and paste in target (leave target on top)
Scroll back to title and see that the target is now empty

**Comment by ghost** [comment]
@cckozie: We can't duplicate this.

**Comment by ghost** [comment]
Confirmed. Optical illusion.

The Project Title chunk is initially not on the screen, so when you do the steps and then scroll up, you think the Story Title was not saved, when in reality the Project Title is showing up.

**Comment by cckozie** [comment]
Agreed.
