### ISSUE TITLE
Inconsistent use of terms

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-requirements#51]
tS 5.0.0
After a “Backup” is performed, the user notification states “Your project has been successfully archived. Thanks.” It should state “Your project has been successfully backed up.”

**Comment by cdwhitfield73** [comment]
this has been fixed

**Comment by RRohrssen** [comment]
@cdwhitfield73 Fixed in both Android and Desktop? Or, was this a desktop only issue?

**Comment by cdwhitfield73** [comment]
@RRohrssen This was a desktop only issue.  It was such a quick fix, no need to create an issue in the desktop repo to account for it!
