### ISSUE TITLE
Unexpected results after a restore

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-requirements#52]
tS 5.0.0 - Windows 10
I have an OBS project on which I performed a backup. I then went into review mode, chose a chunk to edit, made a one word change (actually an insert), and then exited edit mode. I then restored from the previous backup and the change I made in edit mode was still there. I expected it to be overwritten from the backup. Is this the intended behavior?

**Comment by ghost** [comment]
@cckozie This appears to be a bug. From my testing, restoring an existing project is not working. The code is not handling the case with an existing project. AFAICT, it's just erroring out, and that error is not being handled (in fact, it's being ignored).

Also, now that I think about it, we might have an existing Issue for this. @cdwhitfield73 and I (and possibly @neutrinog) have known that this code (`projects.js restoreTargetTranslation` for reference) does not handle overwriting or merging, etc.

**Comment by ghost** [comment]
Confirmed. We have existing Issues in the ts-desktop repo for Merging. As of right now, the ts-desktop code has no way of merging in an existing project. For the Restore to work with an existing project atm, one has to delete the existing project. 

There are several things that can be done.
1. Notify the user if they are restoring an existing project and tell them to delete it first.
2. Delete the existing project and restore from the backup. (No merging.)
3. Merge in data from the backup, preferring new data. (Basic merge.)
4. Do a full merge, allowing them to select which data to accept (a la Git).

Some of these could be temp fixes or be in tandem with Merging being provided as its own option.

**Comment by cdwhitfield73** [comment]
Until git merges have been fully implemented, this has been changed to what you would expect, namely restoring a backed up version of a project completely overwrites an existing project to the backed up version, losing all new changes

**Comment by RRohrssen** [comment]
Issue moved to [unfoldingWord-dev/ts-desktop #480](https://github.com/unfoldingWord-dev/ts-desktop/issues/480) via [**ZenHub.io**](https://www.zenhub.io/)

**Comment by da1nerd** [comment]
Please note the latest specification for restoring a target translation is view able at https://github.com/unfoldingWord-dev/ts-requirements/wiki/Importing-a-Target-Translation#restoring

**Comment by cdwhitfield73** [comment]
this is complete.
