### ISSUE TITLE
File extension always added on backups

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-requirements#54]
tS 5.0.0 - Windows 10
When a backup is performed the system always adds the extension ".tstudio" even when it is already there. My common practice when doing backups is to select a file that is already there (if one exists), and then add/change a number to it. e.g. click on uw-obs-en2.tstudio and change the 2 to a 3. When this is done, the software will create the backup file as uw-obs-en3.tstudio.tstudio.

**Comment by cdwhitfield73** [comment]
Yes, this is an issue, and a fairly easy fix...

**Comment by cdwhitfield73** [comment]
This has been fixed. @RRohrssen do you want to make an issue for this in desktop to account for my time?  The same issue exists for creating pdf's when printing and files when exporting.  I am going to rework those modules too, so maybe one issue to cover all three would suffice.

**Comment by RRohrssen** [comment]
@cckozie Please check this in the next release (7). Once you are comfortable that it is working correctly we can close this out.

Thanks.

**Comment by RRohrssen** [comment]
@neutrinog Shouldn't the android version handle this the same way? (sequential files)

**Comment by da1nerd** [comment]
We shouldn't add them automatically, just confirm they want to overwrite
and make sure to not add the extension twice if the user decides to type it
out.  Right now the android backup/export needs some work. It's just
blindly copying at the moment. We should instead open a mini file browser
so they can choose where to save it. And allow changing the saved file
name. This is all very similar to desktop.

**Comment by RRohrssen** [comment]
@neutrinog I should have checked the requirements that you put together here: https://github.com/unfoldingWord-dev/ts-requirements/wiki/Automatic-Backups

I like the functionality that you've laid out, and what @cckozie suggested. However, we should have it working only one way, according to the spec.

@cdwhitfield73 Let's reconsider rolling forward with the numbering scheme. Isn't the downside of the numbering scheme is that it may leave a lot of files on the device (desktop or android) for the user to clean up outside of the app. Agreed?

**Comment by cdwhitfield73** [comment]
@RRohrssen Ok...now I'm confused.  This issue wasn't about a numbering scheme, it was about the extension getting accidentally duplicated.  That has been fixed.  Desktop now works just as Joel described above. (I also made a note pointing out this confusion on the desktop issue #479)

**Comment by RRohrssen** [comment]
@cdwhitfield73 Yes. I misunderstood the problem here. Thanks for clearing it up.

**Comment by cdwhitfield73** [comment]
This can be closed...
