### ISSUE TITLE
Make source text visible in the 2nd column when translating notes, questions, words

### ISSUE THREAD

**Issue by RRohrssen** [unfoldingWord-dev/ts-requirements#56]
When translating a GL project of Words, Note, and Questions the translators would like to see the bible verses in their target language as well as the English.

If working in a connected solution could the target language be populated with the highest quality language available on Door 43? For example, when starting a new project for notes, words, and questions can we get the source populated with the text of the Level 3 translation populated? If 3 not found, back down to 2, then 1, etc.

If offline, are there options to populate the text from a project locally without opening 2 projects and using copy/paste options to get the text visible while doing note, words, and questions. 

![image](https://cloud.githubusercontent.com/assets/15789352/13849429/1c29bcc4-ec24-11e5-875c-38a7b3d70a47.png)

**Comment by RRohrssen** [comment]
The way this is being done in the field is by switching between a GL translation project to get the target language translation for the specific chunk using windows copy.

Then return to the Notes project and paste that text into the target translation column (#2) in order to have that visible.

**Comment by jag3773** [comment]
If the translation project exists on the device then it will be automatically loaded into the second column.  Please confirm @cdwhitfield73 or @tjklemz .  As I recall, that's how we decided to do this.

**Comment by cdwhitfield73** [comment]
Yes, Jesse you are basically correct.  And I am confused how this even got reported as an issue.  You cannot even start a notes or questions project without first having a standard translation project for that same book/language combo on your project list.  And then that project will be the one that is populated into column two when you open the notes/questions project.  (They shouldn't even be able to paste into column 2, it is just read only.  The scenarios described above should not be happening)

**Comment by RRohrssen** [comment]
@cdwhitfield73 Ok. I'm confused as I just went through this scenario with Peter Schug this morning using Win 5.0 on desktop. He walked me through this for the Tok Pisin language. Column 2 wasn't populated.

Maybe this is a user training issue. @cdwhitfield73 I'll setup a time in slack to see this work/not work with you.

**Comment by ChrisJarka** [comment]
This 'issue' comes up because there is no .tstudio L3 project file for this language. 
Of course I'm interested in 'user training issue' resolutions. :)

**Comment by PSschug** [comment]
@cdwhitfield73 Just to be clear in this case we are talking about OBS. but this will happen more if translators are doing book by book

**Comment by RRohrssen** [comment]
@PSschug I spent some time with @cdwhitfield73 just now. I don't think that this is an issue. But, it's working as designed.

Here are the highlights:
1. Column 1 is always the source translation. Tok Pisin shows up here because it is a GL translation checked to level 3 on Door43.
3. Column 2 is the target translation. This will include text from any other [language-matching] projects that are found locally. So, in your case you found a cheat to get text into column 2 by copy/paste methods on another local project when doing the GL Notes, Questions, and Words project.

It's working as intended. But, I remain open to feedback on this if we need to reopen it or modify it into another issue or feature request.
