### ISSUE TITLE
Write Spec for Scripture Display

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-requirements#7]
We need to finish writing out the desired way that we'll display Scripture (by default) in our apps.  Please finish https://github.com/unfoldingWord-dev/ts-requirements/wiki/USFM-Display .

This will apply to tS Android, tS Desktop, uW App, and uW website.

**Comment by jag3773** [comment]
Note that the \sp definition is the only one that we have actually defined.  The chapter and verse marker definitions were just put there as examples.

**Comment by RRohrssen** [comment]
@sampeckham Pending Sam's input.
