### ISSUE TITLE
Include License File

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-requirements#8]
Android and Desktop need to include a LICENSE file in every repo they create.

This should work: https://github.com/Door43/d43-en/blob/master/legal/license.txt -- but update that to MarkDown format please.

See related issue at https://github.com/unfoldingWord-dev/gogs/issues/3.

**Comment by jag3773** [comment]
Note that there is a Markdown version here: https://git.door43.org/Door43/tw-en/src/master/LICENSE.md .  You can just copy that.

**Comment by RRohrssen** [comment]
Android: https://github.com/unfoldingWord-dev/ts-android/issues/1309
Desktop: https://github.com/unfoldingWord-dev/ts-desktop/issues/394

**Comment by cdwhitfield73** [comment]
This is complete in Desktop
