### ISSUE TITLE
Menu is not hidden after second print request (Win10 and OSX)

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-requirements#80]
If I do a print from the ... menu it works as expected. But if I do a second print without first returning to Home, the ... menu is not hidden after taking the print option.

**Comment by cdwhitfield73** [comment]
This is a glitch in the custom polymer element that we are using for this menu.  I have tried a few things to fix it but was unsuccessful.  Probably need to stop using the polymer element and build our own to get the functionality to work as we want.

**Comment by cdwhitfield73** [comment]
This is complete in Desktop.
