### ISSUE TITLE
More consistent/valuable feedback during i/o operations

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord-dev/ts-requirements#86]
We show the user a progress bar during backup and restore processes. During a project load process we just display the Loading...please wait modal. It would be nice to see the progress bar during the project load process as well, both for consisitency as well as loading a large project on a slow machine can take a fair amount of time where the user is left wondering if it's working or frozen.

**Comment by cdwhitfield73** [comment]
This has already been added to desktop...changes will show up in next Pull Request

**Comment by cdwhitfield73** [comment]
This is complete in Desktop.
