### ISSUE TITLE
Line breaks in tS Translation Academy Projects

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-requirements#89]
The target language translation is not displaying as desired:
- The formatting (extra line breaks and bullets) (Translation Academy projects) disappear when I toggle the page complete. So that the translation is a continuous paragraph. The formatting does appear again when the toggle is slide so I can translate again.
- The target language and source language content is not side-by-side (within a page) for an easy compare.

Would it be possible to split the source language pages by the headings?

**Comment by ChrisJarka** [comment]
Afekhafe Araromi in #translationstudio channel 5/5/16
Another thing I noticed with tS-Android is that the ENTER key is of no use; I guess I may be wrong. But I tried typing in a part of a chunk in the form of poetry, and it still joined every line together.

**Comment by RRohrssen** [comment]
tA is being moved to GOGS by the end of MAY. The WIKI formatting will be transitioned to USFM.

At this time we won't program around the poor WIKI formatting.

**Comment by RRohrssen** [comment]
In Desktop the line breaks do not display correctly until you enter EDIT mode.

**Comment by da1nerd** [comment]
this has been broken up into #111 #112 #113 #114
