### ISSUE TITLE
Create non-blind drafting mode 

### ISSUE THREAD

**Issue by DonRitchey** [unfoldingWord-dev/ts-requirements#9]
This enhancement request is related to Help Desk Ticket 1762:

We are using direct (non-blind) drafting for translating the Gateway Language translation tools (ULB, UDB, Notes, Words). If we are doing that translation in tS, we need to have a non-blind drafting mode for these, so that what they are translating does not get covered up.

**Comment by da1nerd** [comment]
@DonRitchey there is a review mode you can navigate to. It's the third button from the top when you are in your translation.
