### ISSUE TITLE
Provide Gogs URL to tS User on Upload or Publish

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/ts-requirements#93]
When someone does an online backup or when they publish, we should give them the URL of where there content now is in gogs.

**Comment by ChrisJarka** [comment]
I did notice that when I logged into Gogs it took me (using the new user ID) right to my repo. That's very nice but I knew where to go to look (gogs) and the MTT will need to be told that.

**Comment by cdwhitfield73** [comment]
This is a great idea.  So great, that I already added it to desktop last week!

**Comment by cdwhitfield73** [comment]
This is complete in Desktop.

**Comment by da1nerd** [comment]
also in android

**Comment by klappy** [comment]
addressed.
