### ISSUE TITLE
Repeating login required

### ISSUE THREAD

**Issue by ChrisJarka** [unfoldingWord-dev/ts-requirements#99]
I have found that each time I start a new project that I need to go through the login process again (putting in my name and agreeing to SoF, TG, & License)
Is this by design? I'm the only user on the computer....

**Comment by da1nerd** [comment]
No that is a bug

**Comment by ChrisJarka** [comment]
@RRohrssen see Joel's comment - can the status on this issue be changed to 'bug'?

**Comment by cckozie** [comment]
Not an issue in 7.0
